In [10]:
import pandas as pd

data= pd.read_csv("/home/vidhij2/nivi/Nivi_ANCUsers_2023.01.01-2025.01.20.csv")

In [19]:
data2= pd.read_csv("/home/vidhij2/nivi/Nivi_ANCSessions_edited.csv")

In [22]:
data2['questiontime'] = pd.to_datetime(data2['questiontime'], errors='coerce')

# Find the earliest question time
earliest_question_time = data2['questiontime'].min()

earliest_question_time

Timestamp('2024-08-02 00:01:04.305000+0000', tz='UTC')

In [21]:


# Convert the 'questiontime' column to datetime for easier manipulation
data['questiontime'] = pd.to_datetime(data['questiontime'], errors='coerce')

# Find the earliest question time
earliest_question_time = data['questiontime'].min()

earliest_question_time

Timestamp('2024-10-02 00:00:20.451000+0000', tz='UTC')

In [16]:
stage_column = data['stage'].fillna('')  # Handle potential NaN values in the 'stage' column
stages_starting_with_week = stage_column.str.startswith('week').value_counts()

stages_starting_with_week

stage
False    407183
True     123858
Name: count, dtype: int64

In [9]:
df[df['acct'] == 'c328ab6af719f20d24751f31c0e488bd'].shape

(3, 15)

In [2]:
data

,age,gender,acct_creation_date,anc_onboarding_date,due_date,clinic_name,id,acct,session,conversation,stage,question,answer,questiontime,answertime
0,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048648,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,uninitialized,NaN,NaN,2024-10-04 05:15:36.169 +0000,NaN
1,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048649,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,verify_country,NaN,India,2024-10-04 05:15:36.179 +0000,2024-10-04 05:15:36.177 +0000
2,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048650,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,choose-anc-or-pnc,Which situation describes you?\n{{I'm pregnan...,pregnant,2024-10-04 05:15:36.189 +0000,2024-10-04 05:15:54.458 +0000
3,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048671,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,userwantsanctips,NaN,NaN,2024-10-04 05:15:54.437 +0000,NaN
4,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048673,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,APP_ANC,ask_baby_due,NaN,NaN,2024-10-04 05:15:55.108 +0000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531036,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176267,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_question_concern_no_answer_available,uninitialized,üôè Thanks for sharing. I'm currently finding t...,NaN,2025-01-20 17:15:28.920 +0000,NaN
531037,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176268,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_question_concern_no_answer_available,exit,NaN,NaN,2025-01-20 17:15:28.940 +0000,NaN
531038,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176286,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,nlp_maternal_health,end,NaN,NaN,2025-01-20 17:15:32.752 +0000,NaN
531039,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176294,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_journey,check_nlpprompt_response,NaN,default,2025-01-20 17:15:33.897 +0000,2025-01-20 17:15:33.925 +0000
531040,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176295,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_journey,end,NaN,NaN,2025-01-20 17:15:33.907 +0000,NaN

In [14]:
print(data['stage'].value_counts())

stage
uninitialized          79211
end                    22285
nlp_prompt             17662
nlp_maternal_health    16350
exit                   14494
                       ...
gender                     1
age                        1
sms_thanks_msg             1
assessing_readiness        1
ready                      1
Name: count, Length: 342, dtype: int64

In [5]:
df['stage'] = df['stage'].fillna('')  # Replace NaN in 'stage' with empty strings for processing

# Add prefix for rows between week numbers stated in 'stage'
week_prefix = None
for i in range(len(df)):
    if 'week_' in df.iloc[i]['stage']:
        week_prefix = df.iloc[i]['stage'].split('_')[0]  # Extract current week prefix
    elif week_prefix:
        df.at[i, 'stage'] = f"{week_prefix}_{df.iloc[i]['stage']}"

# Display the updated dataset to the user
# tools.display_dataframe_to_user(name="Original Dataset with Updated Week Prefixes", dataframe=data)

In [6]:
df

,age,gender,acct_creation_date,anc_onboarding_date,due_date,clinic_name,id,acct,session,conversation,stage,question,answer,questiontime,answertime
0,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048648,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,uninitialized,NaN,NaN,2024-10-04 05:15:36.169 +0000,NaN
1,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048649,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,verify_country,NaN,India,2024-10-04 05:15:36.179 +0000,2024-10-04 05:15:36.177 +0000
2,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048650,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,choose-anc-or-pnc,Which situation describes you?\n{{I'm pregnan...,pregnant,2024-10-04 05:15:36.189 +0000,2024-10-04 05:15:54.458 +0000
3,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048671,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,userwantsanctips,NaN,NaN,2024-10-04 05:15:54.437 +0000,NaN
4,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048673,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,APP_ANC,ask_baby_due,NaN,NaN,2024-10-04 05:15:55.108 +0000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531036,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176267,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_question_concern_no_answer_available,week_uninitialized,üôè Thanks for sharing. I'm currently finding t...,NaN,2025-01-20 17:15:28.920 +0000,NaN
531037,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176268,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_question_concern_no_answer_available,week_exit,NaN,NaN,2025-01-20 17:15:28.940 +0000,NaN
531038,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176286,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,nlp_maternal_health,week_end,NaN,NaN,2025-01-20 17:15:32.752 +0000,NaN
531039,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176294,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_journey,week_check_nlpprompt_response,NaN,default,2025-01-20 17:15:33.897 +0000,2025-01-20 17:15:33.925 +0000
531040,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176295,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_journey,week_end,NaN,NaN,2025-01-20 17:15:33.907 +0000,NaN

In [26]:
random_acct = data['acct'].dropna().sample(1).iloc[0]

# Filter the dataset for the selected account
filtered_conversation = data[data['acct'] == random_acct]

In [27]:
filtered_conversation

,age,gender,acct_creation_date,anc_onboarding_date,due_date,clinic_name,id,acct,session,conversation,stage,question,answer,questiontime,answertime
295844,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,13588726,f3c672629a26fa4ee830068c0ce48852,ab4543a3e83bcf0fc4b39d1113aeb113,anc_marketing_welcomeblurb,uninitialized,NaN,NaN,2024-10-23 05:28:11.854000+00:00,NaN
295845,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,13588727,f3c672629a26fa4ee830068c0ce48852,ab4543a3e83bcf0fc4b39d1113aeb113,anc_marketing_welcomeblurb,verify_country,NaN,India,2024-10-23 05:28:11.864000+00:00,2024-10-23 05:28:11.779 +0000
295846,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,13588728,f3c672629a26fa4ee830068c0ce48852,ab4543a3e83bcf0fc4b39d1113aeb113,anc_marketing_welcomeblurb,choose-anc-or-pnc,Which situation describes you?\n{{I'm pregnan...,pregnant,2024-10-23 05:28:11.874000+00:00,2024-10-23 05:28:19.783 +0000
295847,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,13588733,f3c672629a26fa4ee830068c0ce48852,ab4543a3e83bcf0fc4b39d1113aeb113,anc_marketing_welcomeblurb,userwantsanctips,NaN,NaN,2024-10-23 05:28:19.850000+00:00,NaN
295848,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,13588734,f3c672629a26fa4ee830068c0ce48852,ab4543a3e83bcf0fc4b39d1113aeb113,APP_ANC,ask_baby_due,NaN,NaN,2024-10-23 05:28:20.650000+00:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295950,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,20933698,f3c672629a26fa4ee830068c0ce48852,3f21cae9eac9174b98e8631ef6f8ce0b,anc_week_28,anc_week28_outro,Remember to take your iron and folic acid (IF...,NaN,2025-01-17 09:04:57.179000+00:00,NaN
295951,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,20933703,f3c672629a26fa4ee830068c0ce48852,3f21cae9eac9174b98e8631ef6f8ce0b,anc_journey,nlp_prompt,Some common topics parents ask about include ...,no,2025-01-17 09:05:10.226000+00:00,2025-01-17 09:06:22.421 +0000
295952,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,20933743,f3c672629a26fa4ee830068c0ce48852,3f21cae9eac9174b98e8631ef6f8ce0b,anc_journey,image_anc,NaN,NaN,2025-01-17 09:06:22.392000+00:00,NaN
295953,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,20933744,f3c672629a26fa4ee830068c0ce48852,3f21cae9eac9174b98e8631ef6f8ce0b,anc_journey,socialsharing_link_message_anc,üå± üöÄ üìà Help askNivi grow! Forward this link an...,NaN,2025-01-17 09:06:22.402000+00:00,NaN
295954,27.0,woman,2024-10-23 05:27:53.211 +0000,2024-10-23 05:28:46.611 +0000,2025-04-18 00:00:00.000 +0000,Dr.Kailashnath Katju Hospital,20933745,f3c672629a26fa4ee830068c0ce48852,3f21cae9eac9174b98e8631ef6f8ce0b,anc_journey,end,NaN,NaN,2025-01-17 09:06:22.412000+00:00,NaN

In [29]:
data['stage'] = data['stage'].fillna('')  # Replace NaN in 'stage' with empty strings for processing

# Add prefix for rows between week numbers stated in 'stage'
week_prefix = None
for i in range(len(data)):
    if 'week_' in data.iloc[i]['stage'] and data.iloc[i]['stage'].split('_')[0]=='week':
        
        week_prefix = data.iloc[i]['stage'].split('_')[1]  # Extract current week prefix
    elif week_prefix:
        data.at[i, 'stage'] = f"{week_prefix}_{data.iloc[i]['stage']}"

In [30]:
data

,age,gender,acct_creation_date,anc_onboarding_date,due_date,clinic_name,id,acct,session,conversation,stage,question,answer,questiontime,answertime
0,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048648,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,uninitialized,NaN,NaN,2024-10-04 05:15:36.169000+00:00,NaN
1,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048649,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,verify_country,NaN,India,2024-10-04 05:15:36.179000+00:00,2024-10-04 05:15:36.177 +0000
2,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048650,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,choose-anc-or-pnc,Which situation describes you?\n{{I'm pregnan...,pregnant,2024-10-04 05:15:36.189000+00:00,2024-10-04 05:15:54.458 +0000
3,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048671,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,anc_marketing_welcomeblurb,userwantsanctips,NaN,NaN,2024-10-04 05:15:54.437000+00:00,NaN
4,36.0,woman,2023-02-08 04:38:28.505 +0000,2024-10-04 05:16:44.842 +0000,2025-03-11 00:00:00.000 +0000,Hamidia Hospital,12048673,a9e58b8699d536eee85c4e9ce106c523,865b6c2fc10e08b6ab966147c68aa655,APP_ANC,ask_baby_due,NaN,NaN,2024-10-04 05:15:55.108000+00:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531036,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176267,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_question_concern_no_answer_available,32_uninitialized,üôè Thanks for sharing. I'm currently finding t...,NaN,2025-01-20 17:15:28.920000+00:00,NaN
531037,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176268,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_question_concern_no_answer_available,32_exit,NaN,NaN,2025-01-20 17:15:28.940000+00:00,NaN
531038,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176286,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,nlp_maternal_health,32_end,NaN,NaN,2025-01-20 17:15:32.752000+00:00,NaN
531039,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176294,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_journey,32_check_nlpprompt_response,NaN,default,2025-01-20 17:15:33.897000+00:00,2025-01-20 17:15:33.925 +0000
531040,27.0,woman,2025-01-20 17:09:02.271 +0000,2025-01-20 17:14:35.841 +0000,2025-06-11 00:00:00.000 +0000,‡¶ú‡ßã‡¶®‡¶æ‡¶ï‡ßÄ ‡¶®‡¶ó‡ß∞,21176295,4f4920185b54bf47af3706711d414484,bfe370c002030ab3e786a0180fde175f,anc_journey,32_end,NaN,NaN,2025-01-20 17:15:33.907000+00:00,NaN

In [31]:
response_data = data.copy()

# Identify rows where 'answer' is not null to count as a response
response_data['response'] = ~response_data['answer'].isnull()

# Group by stage and calculate response rate
response_rate = response_data.groupby('stage')['response'].agg(['sum', 'count'])
response_rate['response_rate'] = (response_rate['sum'] / response_rate['count']) * 100

# Rename columns for clarity
response_rate = response_rate.rename(columns={'sum': 'responses', 'count': 'total_entries'})

In [32]:
response_rate

                          responses  total_entries  response_rate
stage
10_ask_baby_due                   0            125       0.000000
10_ask_baby_due_day               0             74       0.000000
10_ask_baby_due_month             0             75       0.000000
10_ask_clinic_name                0             27       0.000000
10_ask_clinic_to_go               0             76       0.000000
...                             ...            ...            ...
week_40                         920           5634      16.329428
week_40_visit_reminder            0            926       0.000000
week_41                        1164           6441      18.071728
week_41_visit_assessment          0           1251       0.000000
welcome                           0              1       0.000000

[2177 rows x 3 columns]

In [33]:
response_data['question'] = response_data['question'].fillna('No Question')  # Replace NaN questions with a placeholder

# Group by stage and question, then calculate response rate
response_rate_with_question = response_data.groupby(['stage', 'question'])['response'].agg(['sum', 'count'])
response_rate_with_question['response_rate'] = (response_rate_with_question['sum'] / response_rate_with_question['count']) * 100

# Rename columns for clarity
response_rate_with_question = response_rate_with_question.rename(
    columns={'sum': 'responses', 'count': 'total_entries'}
)

In [34]:
response_rate_with_question

                                      responses  total_entries  response_rate
stage                    question
10_ask_baby_due          No Question          0            125       0.000000
10_ask_baby_due_day      No Question          0             74       0.000000
10_ask_baby_due_month    No Question          0             75       0.000000
10_ask_clinic_name       No Question          0             27       0.000000
10_ask_clinic_to_go      No Question          0             76       0.000000
...                                         ...            ...            ...
week_40                  No Question        920           5634      16.329428
week_40_visit_reminder   No Question          0            926       0.000000
week_41                  No Question       1164           6441      18.071728
week_41_visit_assessment No Question          0           1251       0.000000
welcome                  No Question          0              1       0.000000

[2604 rows x 3 columns]

In [42]:
sorted_response_weekly= response_rate_with_question.sort_values(
    by='total_entries', ascending=False
)

In [46]:
# output_path = '/mnt/data/Filtered_Conversation.csv'
sorted_response_weekly.to_csv("sorted_response_weekly_tilljan2025.csv")

In [47]:
pd.read_csv("/home/vidhij2/nivi/sorted_response_weekly_tilljan2025.csv")

,stage,question,responses,total_entries,response_rate
0,week_41,No Question,1164,6441,18.071728
1,41_uninitialized,No Question,1821,6216,29.295367
2,week_40,No Question,920,5634,16.329428
3,week_38,No Question,1101,5262,20.923603
4,week_39,No Question,1023,5121,19.976567
...,...,...,...,...,...
2599,10_uninitialized,Are you experiencing any of these symptoms?\n...,1,1,100.000000
2600,10_text_1,Thank you for letting me know.,0,1,0.000000
2601,10_sti,No Question,0,1,0.000000
2602,10_explainer_1,Wearing loose clothing and washing your priva...,0,1,0.000000
2603,10_explainer_1,"These are signs of urinary infection, which i...",0,1,0.000000

In [43]:
sorted_response_weekly

                                                                     responses  \
stage            question
week_41          No Question                                              1164
41_uninitialized No Question                                              1821
week_40          No Question                                               920
week_38          No Question                                              1101
week_39          No Question                                              1023
...                                                                        ...
10_uninitialized  Are you experiencing any of these symptoms?\n\...          1
10_text_1         Thank you for letting me know.                             0
10_sti           No Question                                                 0
10_explainer_1    Wearing loose clothing and washing your privat...          0
                  These are signs of urinary infection, which is...          0

                                                                     total_entries  \
stage            question
week_41          No Question                                                  6441
41_uninitialized No Question                                                  6216
week_40          No Question                                                  5634
week_38          No Question                                                  5262
week_39          No Question                                                  5121
...                                                                            ...
10_uninitialized  Are you experiencing any of these symptoms?\n\...              1
10_text_1         Thank you for letting me know.                                 1
10_sti           No Question                                                     1
10_explainer_1    Wearing loose clothing and washing your privat...              1
                  These are signs of urinary infection, which is...              1

                                                                     response_rate
stage            question
week_41          No Question                                             18.071728
41_uninitialized No Question                                             29.295367
week_40          No Question                                             16.329428
week_38          No Question                                             20.923603
week_39          No Question                                             19.976567
...                                                                            ...
10_uninitialized  Are you experiencing any of these symptoms?\n\...     100.000000
10_text_1         Thank you for letting me know.                          0.000000
10_sti           No Question                                              0.000000
10_explainer_1    Wearing loose clothing and washing your privat...       0.000000
                  These are signs of urinary infection, which is...       0.000000

[2604 rows x 3 columns]